#!/usr/bin/env bash
# www
sub_domains=("www" "lb-01" "web-01" "web-02")
print_subdom()
{
	domain=$1
	sub_domain=$2
	dig "$sub_domain"."$domain" | grep -A1 'ANSWER SECTION:' | tail -1 | awk -v dom="$sub_domain" '{print "The subdomain " dom " is a " $4 " record and points to " $5}'
}
if (( "$#" == 1 ))
then
	for sub_dom in "${sub_domains[@]}"
	do
		print_subdom "$1" "$sub_dom"
	done
elif (( "$#" == 2 ))
then
	print_subdom "$1" "$2"
fi



# display_info() {
#     local domain=$1
#     local subdomain=$2
#     local record_type

#     if [[ -z $subdomain ]]; then
#         subdomain_list=("www" "lb-01" "web-01" "web-02")
#     else
#         subdomain_list=("$subdomain")
#     fi

#     for sub in "${subdomain_list[@]}"; do
#         # record_type=$(dig +short "$sub.$domain" | awk 'NR==1{print $9}')
#         # destination=$(dig +short "$sub.$domain" | awk 'NR==1{print $1}')
#         record_type=$(dig +short "$sub.$domain" | grep -A1 'ANSWER SECTION:' |  tail -1 | awk -v dom="$sub" '{print "$4"}')
#         destination=$(dig +short "$sub.$domain" | grep -A1 'ANSWER SECTION:' |  tail -1 | awk -v dom="$sub" '{print $5}')

#         echo "The subdomain $sub is $record_type record and points to $destination"
#         done
# }

# # Entry point
# if [[ $# -eq 0 ]]; then
#     echo "Error: Please provide at least the domain name as an argument."
#     exit 1
# fi

# domain=$1
# subdomain=$2

#display_info "$domain" "$subdomain"
#displays information about subdomains
