#!/usr/bin/env bash
# ACTION: Script transfers a file from our client to a server
# accepts 4 parameters:
# 1 the path to the file to be transferred
# 2 the IP of the server we want to transfer the file to 
# 3 The username scp connects with
# 4 the path to the ssh private key that scp uses
# --------------------------------------------------
# Display Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY if less than 3 parameters passed
# scp must transfer the file to the user home directory ~/
# Strick host key checking must be disabled when using scp
if [ "$#" -lt 3 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~/
fi