#!/usr/bin/bash
# install NGINX web server on server

apt-get update
apt-get -y install nginx
ufw allow "Nginx HTTP"
mkdir -p /var/www/html
chmod -R 755 /var/www
echo "Hello World!" | sudo tee /var/www/html/index.html
# Block server config
SERVER_CONFIG=\
"server {
    	listen 80 default_server;
    	listen [::]:80 default_server;

    	root /var/www/html;
    	index index.html index.htm index.nginx-debian.html;

  	  server_name _;

  	  location / {
        		try_files \$uri \$uri/ =404;
   	 }
}"
bash -c "echo -e '$SERVER_CONFIG' > /etc/nginx/sites-enabled/default"

if [ "$(pgrep -c nginx)" -le 0 ]; then
	sudo service nginx start
else
	sudo service nginx restart
fi