#!/usr/bin/env bash
# install nginx
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow "Nginx HTTP"
sudo mkdir -p /var/www/html /var/www/error
chmod -R 755 /var/www
echo "Hello World!" | sudo tee  /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee  /var/www/error/404.html
SERVER_CONFIG=\
"server {
	listen 80 default_server;
	listen [::]:80 default_server;
	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;
	server_name _;

	location / {
		try_files \$uri \$uri/ =404;
        add_header X-Served-By \$hostname;
	}

	if (\$request_filename ~ redirect_me){
		rewrite ^ https://twitter.com/obigvee permanent;
	}
    error_page 404 /404.html;
    location = /404.html {
        root /var/www/error/;
        internal;
        add_header X-Served-By \$hostname;

    }
}"

sudo bash -c "echo -e '$SERVER_CONFIG' > /etc/nginx/sites-enabled/default"

if [ "$(pgrep -c nginx)" -le 0 ]; then
	sudo service nginx start
else
	sudo service nginx restart
fi