#!/usr/bin/env bash
# install and configure HAproxy LB on server lb-01
 
# install haproxy 
sudo apt-get -y update
sudo apt-get -y install haproxy

# Configure haproxy
cat << EOF | sudo tee -a /etc/haproxy/haproxy.cfg

frontend servers
        bind :80
        default_backend webservers

backend webservers
        balance roundrobin
        server 96570-web-01 100.25.144.235:80 check
	    server 96570-web-02 3.85.136.215:80 check

EOF

# Restart haproxy using init script
sudo /etc/init.d/haproxy restart