#!/usr/bin/env bash

# Get the current dae in the required format (day-month-year)
CURRENT_DATE=$(date +"%d-%m-%Y")

# Mysql dump fileName
DUMP_FILE="backup.sql"

# Compressed archive name
ARCHIVE_NAME="$CURRENT_DATE.tar.gz"

# Generate MySQL dump
mysqldump --all-databases -uroot -p"$1"> "$DUMP_FILE"

# compress the mySQL dump
tar czvf "$ARCHIVE_NAME" "$DUMP_FILE"
