#!/usr/bin/env bash

# check if the password argument is provided
if [ $# -ne 1 ]; then
    echo "Usage: $0 <mysql_password>"
    exit 1
fi

# MySQL root password
MYSQL_PASSWORD="$1"

# Get the current dae in the required format (day-month-year)
CURRENT_DATE=$(date +"%d-%m-%Y")

# Mysql dump fileName
DUMP_FILE="backup.sql"

# Compressed archive name
ARCHIVE_NAME="$CURRENT_DATE.tar.gz"

# Directory to store the backups
BACKUP_DIR="/path/to/backup/directory"

# create the backup dir if it doesn't exist
mkdir -p "$BACKUP_DIR"

# Generate MySQL dump
mysqldump -u root -p"$MYSQL_PASSWORD" --all-databases > "$BACKUP_DIR/$DUMP_FILE"

# compress the mySQL dump
tar czvf "$BACKUP_DIR/ARCHIVE_NAME" -C "$BACKUP_DIR" "DUMP_FILE"

# Remove the uncompressed dump file
rm "$BACKUP_DIR/$DUMP_FILE"

echo "Backup completed. The compressed archive is stored as: $ARCHIVE_NAME"