#!/usr/bin/env bash
# script pings an ip address passed as an argument
# REQUIREMENT 
# accepts a string a an argument
# displays Usage: 5-is_the_host_on_the_network ip if no args pass
# pings ip * 5
if [ "$#" -eq 0 ] 
then
	echo 'Usage: 5-is_the_host_on_the_network {IP_ADDRESS}'
else
	ping -c 5 "$1"
fi
