#!/bin/bash
# https://www.futurelearn.com/info/courses/linux-for-bioinformatics/0/steps/201767#:~:text=A%20symlink%20is%20a%20symbolic,directory%20in%20any%20file%20system.
#ln-> link command
# -s -> flag which specifies that the link should be soft === -symbolic
# the ln command creates a hard link by defualt
# /bin/ls -> path of file/folder to link (which is the file/folder you want to create shortcut for)
# __ls__ -> path to link itself (where you want the shorcut to be placed)
ln -s /bin/ls __ls__
