#!/usr/bin/env bash
# script:
# Creates the file /var/run/myscript.pid containing its PID
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal
lean_up_action='rm /var/run/myscript.pid; exit $?'

echo $$ > "/var/run/myscript.pid"
trap 'echo "I hate the kill command"; '"$clean_up_action" SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap ''"$clean_up_action" SIGQUIT

while true; do
  echo "To infinity and beyond"
done
