#!/usr/bin/env bash
# write Bash script displays numbers from 1 to 100
#Requirements:

#Displays FizzBuzz when the number is a multiple of 3 and 5
#Displays Fizz when the number is multiple of 3
#Displays Buzz when the number is a multiple of 5
#Otherwise, displays the number
#In a list format
star=1
end=100
for  ((star; star <= end; star++))
do
	if [ $((star%3)) -eq 0 ];
	then
		if [ $((star%5)) = 0 ];
		then
			echo "FizzBuzz"
		else
			echo "Fizz"
		fi
	elif [ $((star%5)) -eq 0 ]
	then
		echo "Buzz"
	else
		echo "$star"
	fi
done
