#!/usr/bin/env bash
# 5-4_bad_luck_8_is_your_chance
bl="bad luck"
gl="good luck"
var="Best School"
count=1
#for (( = 1; i <= 10; i++))
while [ "$count" -lt 10 ]
do

	if [ "$count" -eq 4 ]
	then 
		echo "$bl"
	elif [ "$count" -eq 8 ]
	then
		echo "$gl"
	else
		echo "$var"
	fi
	count="$((count + 1))"
done 
