#!/usr/bin/env bash
# script loops from 1 to 10 and
# displays bad luck for the 4th loop iteration
# displays good luck for the 8th loop iteration
# displays Best School for the other iterations

name="Best School"
count=0
limit=10
while [ "$count" -lt "$limit" ]
do
	if [ "$count" -eq 4 ]
	then
		echo "bad luck"
	elif [ "$count" -eq 8 ]
	then
		echo "good luck"
	else
		echo "$name"
	fi
	count=$((count+1))
done
