#!/usr/bin/env bash
# script displays numbers from 1 to 20 and 
# displays 4 and then bad luck from China for the 4th loop iteration
# displays 9 and then bad luck from Japan for the 9th loop iteration
# displays 17 and then bad luck from Italy for the 17th loop iteration
start=1
end=20
while [ "$start" -le "$end" ]
do
echo "$start"
	if [ "$start" -eq 4 ]
	then
		echo "bad luck from China"
	elif [ "$start" -eq 9 ]
	then
		echo "bad luck from Japan"
	elif [ "$start" -eq 17 ]
	then
		echo "bad luck from Italy"
	fi
start=$((start+1))
done

