#!/usr/bin/env bash
# script displays the time for 12 hours and 59 mins
# display hours 0 to 12
# display minutes from 1 to 59
# Requirements:

# You must use the while loop (for and until are forbidden)
#star=1
#end=60
hour=0
while [ "$hour" -le 12 ]
do 
	echo "Hour: $hour";
	star=1
	while [ "$star" -lt 60 ]
	do
		echo "$star";
		star=$((star+1));
	done
	hour=$((hour+1))
done
