#!/usr/bin/env bash
# Bash Script displays
# The Content of the current directory
# in a list format
# where only the part of the name after the first dash is displayed 

#Requirements:

#You must use the for loop (while and until are forbidden)
#Do not display hidden files
for i in *
do
	echo "$i" | cut -d '-' -f 2;
done
