#!/usr/bin/env bash
# script displays all active IPv4 IPs on the machine
#ifconfig | grep "inet addr" | cut -f2 -d " " | cut -f1 -d ":"
ifconfig | grep -Po 'inet addr:\K\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}'