#!/usr/bin/env bash
# Run Nignx as Nginx

# allow nginx user account to read nginx.conf
chmod 644 /etc/nginx/nginx.conf

# Set nginx to listen on all active IPS and port 8080
sed -i 's/80/8080/' /etc/nginx/sites-available/default

# Stop Apache2 (if running)
pkill apache2 

# Restart nginx to apply the changes
su nginx -c  '/etc/init.d/nginx restart'