#!/usr/bin/env bash
# Run Nignx as Nginx


# Set nginx to listen on all active IPS and port 8080
sed -i 's/listen 80;/listen 8080;/g' /etc/nginx/sites-available/default

# Set nginx to run as the nginx user
sed -i 's/user www-data;/user nginx;/g' /etc/nginx/nginx/conf

# allow nginx user account to read nginx.conf
chmod 644 /etc/nginx/nginx.conf

# Stop Apache2 (if running)
pkill apache2 

# Restart nginx to apply the changes
service nginx restart