#!/usr/bin/env bash
# rewrite task 1 Run Nginx as Nginx user in 7 lines or less
chmod 644 /etc/nginx/nginx.conf
sed -i 's/80/8080/' /etc/nginx/sites-available/default
pkill apache2
su nginx -c '/etc/init.d/nginx restart'